modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "jjbamusic"
version = "${version}"
displayName = "JoJo's Bizzare Adventure Music"
authors = "JCraft EoE Team"
description = '''
JJBA music discs for Minecraft
'''
logoFile = "icon.png"

[[dependencies.jjbamusic]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jjbamusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"
